 
 

#ifndef DRED_CONFIG_H
#define DRED_CONFIG_H

 
#define DRED_EXTENSION_ID 126

 
#define DRED_EXPERIMENTAL_VERSION 10
#define DRED_EXPERIMENTAL_BYTES 2


#define DRED_MIN_BYTES 8

 
#define DRED_SILK_ENCODER_DELAY (79+12-80)
#define DRED_FRAME_SIZE 160
#define DRED_DFRAME_SIZE (2 * (DRED_FRAME_SIZE))
#define DRED_MAX_DATA_SIZE 1000
#define DRED_ENC_Q0 6
#define DRED_ENC_Q1 15

 
#define DRED_MAX_LATENTS 26
#define DRED_NUM_REDUNDANCY_FRAMES (2*DRED_MAX_LATENTS)
#define DRED_MAX_FRAMES (4*DRED_MAX_LATENTS)

#endif
